name: first_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  hive: ^2.2.3
  flutter_localization: ^0.1.12
  easy_localization: ^3.0.2
  logger: ^1.4.0
  easy_dynamic_theme: ^2.3.1
  dynamic_color: ^1.4.0
  sliver_tools: ^0.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

  build_runner: ^2.2.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "image_path_ios"
  image_path: "assets/icon/potato.jpg"
  image_path_ios: "assets/icon/chicken.jpg"

flutter:
  uses-material-design: true

  